# Generated by Django 5.0.2 on 2024-03-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('company_name', models.CharField(max_length=40)),
                ('job_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('education_name', models.CharField(max_length=40)),
                ('education_info', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=40)),
                ('portfolio_file', models.FileField(upload_to='uploads/portfolio')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PriorResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_resume_name', models.CharField(max_length=40)),
                ('prior_resume_file', models.FileField(upload_to='uploads/resume')),
            ],
            options={
                'db_table': 'prior_resumes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('project_name', models.CharField(max_length=40)),
                ('project_detail', models.TextField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(default='', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('introduction', models.TextField(blank=True, default='', null=True)),
                ('job_group', models.CharField(default='', max_length=20)),
                ('job_role', models.CharField(default='', max_length=20)),
                ('career_length', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True, default='[]', null=True)),
                ('work_type', models.TextField(default='')),
                ('min_hour_pay', models.IntegerField(default=0)),
                ('max_hour_pay', models.IntegerField(default=50)),
                ('min_month_pay', models.IntegerField(default=0)),
                ('max_month_pay', models.IntegerField(default=1000)),
                ('commute_type', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('performance_name', models.CharField(max_length=40)),
                ('performance_detail', models.TextField()),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.career')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
    ]
