# Generated by Django 5.0.2 on 2024-02-29 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('company_name', models.CharField(max_length=40)),
                ('job_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('education_name', models.CharField(max_length=40)),
                ('education_info', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(max_length=40)),
                ('portfolio_file', models.FileField(upload_to='uploads/portfolio')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PriorResume',
            fields=[
                ('prior_resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('prior_resume_name', models.CharField(max_length=40)),
                ('prior_resume_file', models.FileField(upload_to='uploads/resume')),
            ],
            options={
                'db_table': 'prior_resumes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('project_name', models.CharField(max_length=40)),
                ('project_detail', models.TextField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_name', models.CharField(max_length=20)),
                ('is_default', models.BooleanField()),
                ('introduction', models.TextField(blank=True, null=True)),
                ('job_group', models.CharField(max_length=20)),
                ('job_role', models.CharField(max_length=20)),
                ('career_length', models.IntegerField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('work_type', models.TextField()),
                ('minimum_pay', models.IntegerField()),
                ('maximum_pay', models.IntegerField()),
                ('commute_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.IntegerField()),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('performance_name', models.CharField(max_length=40)),
                ('performance_detail', models.TextField()),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.career')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
    ]
