# Generated by Django 5.0.2 on 2024-02-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
