# Generated by Django 5.0.2 on 2024-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_resume_is_uploaded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="career_length",
            new_name="career_year",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="min_hour_pay",
            new_name="duration_start",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="is_uploaded",
            new_name="is_submitted",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="work_type",
            new_name="keyword",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="resume_name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="max_hour_pay",
        ),
        migrations.AddField(
            model_name="resume",
            name="duration_end",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="resume",
            name="introduction",
            field=models.TextField(default=""),
        ),
    ]
