# Generated by Django 5.0.2 on 2024-04-05 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_rename_career_length_resume_career_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="resume_id",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="education",
            old_name="resume_id",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="performance",
            old_name="career_id",
            new_name="career",
        ),
        migrations.RenameField(
            model_name="portfolio",
            old_name="resume_id",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="priorresume",
            old_name="resume_id",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="resume_id",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="user_id",
            new_name="user",
        ),
    ]
