# Generated by Django 5.0.2 on 2024-04-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_rename_resume_id_career_resume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="careers",
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="career",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="resume.career",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="priorresume",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prior_resumes",
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resume.resume",
            ),
        ),
    ]
