# Generated by Django 5.0.2 on 2024-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_alter_career_resume_alter_education_resume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="career_year",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="resume",
            name="commute_type",
            field=models.CharField(default="희망 근무 형태", max_length=20),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_group",
            field=models.CharField(default="직군", max_length=20),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_role",
            field=models.CharField(default="직무", max_length=20),
        ),
    ]
