# Generated by Django 5.0.2 on 2024-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_alter_resume_introduction_alter_resume_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="company_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="career",
            name="end_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="career",
            name="job_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="career",
            name="start_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_info",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="performance",
            name="end_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="performance",
            name="performance_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="performance_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="performance",
            name="start_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="portfolio_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="priorresume",
            name="prior_resume_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_year_month",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
