# Generated by Django 5.0.2 on 2024-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_alter_career_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="career",
            name="job_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_info",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="performance",
            name="performance_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="portfolio_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="priorresume",
            name="prior_resume_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_group",
            field=models.CharField(default="직군", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="job_role",
            field=models.CharField(default="직무", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
