# Generated by Django 5.0.2 on 2024-02-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('business_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'enterprise_users',
            },
        ),
        migrations.CreateModel(
            name='SeniorUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'senior_users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.enterpriseuser')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.senioruser')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
