# Generated by Django 5.0.2 on 2024-02-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile/enterprise"
            ),
        ),
        migrations.AddField(
            model_name="senioruser",
            name="default_resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume.resume",
            ),
        ),
        migrations.AddField(
            model_name="senioruser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profile/senior"
            ),
        ),
    ]
