# Generated by Django 5.0.2 on 2024-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senioruser',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/profile/senior'),
        ),
    ]
