# Generated by Django 5.0.2 on 2024-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_enterpriseuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile/enterprise'),
        ),
        migrations.AlterField(
            model_name='senioruser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile/senior'),
        ),
    ]
