# Generated by Django 5.0.2 on 2024-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_enterpriseuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='senioruser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/profile/default_profile.png', upload_to='uploads/profile/'),
        ),
    ]
