# Generated by Django 5.0.2 on 2024-05-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_enterpriseuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='company',
            field=models.CharField(default='삼성전자', max_length=20),
        ),
    ]
