# Generated by Django 5.0.2 on 2024-05-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggest", "0024_payment"),
        ("users", "0010_review_tags_alter_review_comment_alter_review_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="suggest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="suggest.suggest",
            ),
        ),
    ]
