# Generated by Django 5.0.2 on 2024-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_review_suggest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
