# Generated by Django 5.0.2 on 2024-02-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendResult',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
            ],
            options={
                'db_table': 'recommend_results',
            },
        ),
        migrations.CreateModel(
            name='RecommendedResume',
            fields=[
                ('recommended_resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('comment', models.CharField(max_length=255, null=True)),
                ('recommend_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.recommendresult')),
            ],
            options={
                'db_table': 'recommended_resumes',
            },
        ),
    ]
