# Generated by Django 5.0.2 on 2024-05-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_remove_enterpriseuser_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('amount_info', models.CharField(max_length=300)),
                ('aid', models.CharField(default='', max_length=20)),
                ('tid', models.CharField(default='', max_length=20)),
                ('payment_method_type', models.CharField(max_length=10)),
                ('card_info', models.CharField(default='', max_length=300)),
                ('created_at', models.CharField(default='', max_length=20)),
                ('approved_at', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
