# Generated by Django 5.0.2 on 2024-05-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_remove_enterpriseuser_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('aid', models.CharField(default='', max_length=20)),
                ('tid', models.CharField(default='', max_length=20, unique=True)),
                ('payment_method_type', models.CharField(default='', max_length=10)),
                ('card_info', models.TextField(blank=True, default='', null=True)),
                ('amount_info', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.CharField(default='', max_length=20)),
                ('approved_at', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year_month', models.CharField(blank=True, max_length=7)),
                ('end_year_month', models.CharField(blank=True, max_length=7)),
                ('pay', models.IntegerField()),
                ('duraton', models.IntegerField()),
                ('job_description', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
                ('senior', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.senioruser')),
            ],
            options={
                'db_table': 'suggests',
            },
        ),
    ]
