# Generated by Django 5.0.2 on 2024-05-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggest',
            old_name='duraton',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='suggest',
            name='end_year_month',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='start_year_month',
            field=models.CharField(max_length=7),
        ),
    ]
