# Generated by Django 5.0.2 on 2024-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0004_suggest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='commute_type',
            field=models.CharField(default='희망 근무 형태', max_length=20),
        ),
    ]
