# Generated by Django 5.0.2 on 2024-05-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0010_alter_career_company_name_alter_career_job_name_and_more'),
        ('suggest', '0007_remove_suggest_enterprise_remove_suggest_resume_and_more'),
        ('users', '0009_enterpriseuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('aid', models.CharField(default='', max_length=20)),
                ('tid', models.CharField(default='', max_length=20, unique=True)),
                ('payment_method_type', models.CharField(default='', max_length=10)),
                ('card_info', models.TextField(blank=True, default='', null=True)),
                ('amount_info', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.CharField(default='', max_length=20)),
                ('approved_at', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commute_type', models.CharField(default='희망 근무 형태', max_length=20)),
                ('start_year_month', models.CharField(max_length=7)),
                ('end_year_month', models.CharField(max_length=7)),
                ('pay', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('job_description', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('enterprise', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.enterpriseuser')),
                ('resume', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='resume.resume')),
                ('senior', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.senioruser')),
            ],
            options={
                'db_table': 'suggests',
            },
        ),
    ]
