# Generated by Django 5.0.2 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggest',
            old_name='is_read',
            new_name='is_senior_read',
        ),
        migrations.AddField(
            model_name='suggest',
            name='is_enterprise_read',
            field=models.BooleanField(default=True),
        ),
    ]
