# Generated by Django 5.0.2 on 2024-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0009_rename_is_read_suggest_is_senior_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
