# Generated by Django 5.0.2 on 2024-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0010_suggest_is_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
