# Generated by Django 5.0.2 on 2024-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0012_remove_suggest_is_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='suggest',
            name='status',
            field=models.CharField(default='is_pending', max_length=20),
        ),
    ]
