# Generated by Django 5.0.2 on 2024-05-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0013_remove_suggest_is_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggest',
            old_name='status',
            new_name='progress',
        ),
    ]
