# Generated by Django 5.0.2 on 2024-05-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0015_payment_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='suggest',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payments', to='suggest.suggest'),
        ),
    ]
