# Generated by Django 5.0.2 on 2024-05-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0019_alter_payment_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
