# Generated by Django 5.0.2 on 2024-05-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0020_remove_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
