# Generated by Django 5.0.2 on 2024-05-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0024_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
