version: '3.4'

services:
  es:
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es
    environment:
      - network.host=0.0.0.0
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false 
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data

  nginx:
    build: ./nginx
    ports: # 호스트 포트와 연결
      - "80:80"
    volumes:
      - static:/usr/src/app/static
      - ./static/drf-yasg:/usr/src/app/static/drf-yasg
    depends_on: 
      - web
    logging:
      options:
        max-size: 10m

  web:
    build:
      context: .
      dockerfile: ./Dockerfile 
    volumes: 
      - .:/app
      - static:/app/static
      - media:/app/media
    expose: # 도커 컨테이너끼리만 내부적으로 포트 연결
      - "8000"
    env_file:
      - dasi/.env
    deploy:
      resources:
        limits:
          cpus: '0.5'  # CPU 코어의 50%만 사용
          memory: '512M'  # 메모리 제한
    logging:
      options:
        max-size: 10m
    depends_on:
      - es

volumes:
  static:
  media:
  data:
