version: '3.4'

services: 
  nginx:
    build: ./nginx
    ports: # 호스트 포트와 연결
      - "80:80"
    volumes:
      - static:/usr/src/app/static
      - ./static/drf-yasg:/usr/src/app/static/drf-yasg
      - media:/usr/src/app/media
    depends_on: 
      - web
    logging:
      options:
        max-size: 10m

  web:
    build:
      context: .
      dockerfile: ./Dockerfile 
    volumes: 
      - .:/usr/src/app
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose: # 도커 컨테이너끼리만 내부적으로 포트 연결
      - "8000"
    env_file:
      - dasi/.env
    deploy:
      resources:
        limits:
          cpus: '0.5'  # CPU 코어의 50%만 사용
          memory: '512M'  # 메모리 제한
    logging:
      options:
        max-size: 10m

volumes:
  static:
  media:
